version: '3.8'

services:
  backend:
    image: ${BACKEND_IMAGE:-finsy-backend:latest}
    container_name: finsy-backend-prod
    ports:
      - "5000:5000"
    environment:
      # Variables que coinciden con tu código JS (process.env.DB_HOST, etc.)
      - DB_HOST=172.31.44.216
      - DB_USER=root
      - DB_PASSWORD=12345678  # Asegúrate de que coincida con la DB en AWS
      - DB_NAME=Finanzas
      - NODE_ENV=production
    restart: always
    networks:
      - finsy-network

  frontend:
    image: ${FRONTEND_IMAGE:-finsy-frontend:latest}
    container_name: finsy-frontend-prod
    ports:
      - "8081:80"
    depends_on:
      - backend
    environment:
      # Usamos la IP Pública del App-Server para que los clientes lleguen al API
      - REACT_APP_API_URL=http://98.81.9.103:5000
    restart: always
    networks:
      - finsy-network

networks:
  finsy-network:
    driver: bridge